### ISSUE TITLE
Docker image missing modules

### ISSUE THREAD

**Issue by bayraktar1** [RitataLU/MethylC-analyzer#3]
Hello,

I am working on a HPC so I have to use singularity instead of docker. After pulling the image I get the following error:

```
(singularityEnv) dogukan@mutant33:[SCREEN]:~/methylc:singularity run docker://peiyulin/methylc:V1.0
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
INFO:    Creating SIF file...
INFO:    Converting SIF file to temporary sandbox...
Singularity> python MethylC-analyzer/scripts/MethylC.py --help
Traceback (most recent call last):
  File "/home/dogukan/methylc/MethylC-analyzer/scripts/MethylC.py", line 5, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

It seems like pandas is not installed in the image.

**Comment by beritlin** [comment]
Hello bayraktar1,

Based on the traceback you provided, it appears that you are still running the code on your local system instead of within the Docker image. Please ensure that you have followed the Docker tutorial provided here: [Tutorial_Docker.md](https://github.com/RitataLU/MethylC-analyzer/blob/master/Tutorial_Docker.md). This tutorial will guide you through the steps to properly set up and run the code within the Docker image.

**Comment by bayraktar1** [comment]
> Hello bayraktar1,
> 
> Based on the traceback you provided, it appears that you are still running the code on your local system instead of within the Docker image. Please ensure that you have followed the Docker tutorial provided here: [Tutorial_Docker.md](https://github.com/RitataLU/MethylC-analyzer/blob/master/Tutorial_Docker.md). This tutorial will guide you through the steps to properly set up and run the code within the Docker image.

Hello,

Thank you for your response!

It seems like the code was indeed not running within the image. I had to bind my current directory to the /app directory in the image as described in the Docker tutorial.

For anyone that also works with singularity the command looks like this:
```
singularity run --bind $(pwd):/app docker://peiyulin/methylc:V1.0  python /MethylC-analyzer/scripts/MethylC.py -h
```
